version: '3'
services:
  play:
    container_name: play 
    image: cescoferraro/play
    build: 
      context: ./build
      dockerfile: ./stage/playBinary/Dockerfile
    ports:
     - "9000:9000"
    environment:
      - VIRTUAL_HOST=play.cescoferraro.xyz
      - CERT_NAME=shared
